name = "TestJuliaLowering"
uuid = "bf4868c1-a219-4035-92b3-7fed6d0f472f"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[deps]
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
JuliaLowering = "f3c80556-a63f-4383-b822-37d64f81a311"

[sources]
JuliaSyntax = {path = "sources/JuliaSyntax"}
JuliaLowering = {path = "sources/JuliaLowering"}
Compiler = {path = "sources/Compiler"}
# CompilerDevTools = {path = "sources/Compiler/extras/CompilerDevTools"}

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
Compiler = "807dbc54-b67e-4c79-8afb-eafe4df6f2e1"
# CompilerDevTools = "92b2d91f-d2bd-4c05-9214-4609ac33433f"

[targets]
test = ["Test", "FileWatching", "REPL", "Markdown", "Jive", "Compiler"]
